/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package google_maps_in_flutter

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'google_maps_in_flutter.greeting' plugin.
 */
class Google_maps_in_flutterPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("google_maps_in_flutter.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
